# @generated by generate_proto_mypy_stubs.py.  Do not edit!
import sys
from google.protobuf.descriptor import (
    Descriptor as google___protobuf___descriptor___Descriptor,
    EnumDescriptor as google___protobuf___descriptor___EnumDescriptor,
)

from google.protobuf.internal.containers import (
    RepeatedCompositeFieldContainer as google___protobuf___internal___containers___RepeatedCompositeFieldContainer,
    RepeatedScalarFieldContainer as google___protobuf___internal___containers___RepeatedScalarFieldContainer,
)

from google.protobuf.message import (
    Message as google___protobuf___message___Message,
)

from typing import (
    Iterable as typing___Iterable,
    List as typing___List,
    Optional as typing___Optional,
    Text as typing___Text,
    Tuple as typing___Tuple,
    Union as typing___Union,
    cast as typing___cast,
)

from typing_extensions import (
    Literal as typing_extensions___Literal,
)


builtin___bool = bool
builtin___bytes = bytes
builtin___float = float
builtin___int = int
builtin___str = str
if sys.version_info < (3,):
    builtin___buffer = buffer
    builtin___unicode = unicode


class Version(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    version = ... # type: builtin___int
    release = ... # type: typing___Text
    os = ... # type: typing___Text
    os_version = ... # type: typing___Text

    def __init__(self,
        *,
        version : typing___Optional[builtin___int] = None,
        release : typing___Optional[typing___Text] = None,
        os : typing___Optional[typing___Text] = None,
        os_version : typing___Optional[typing___Text] = None,
        ) -> None: ...
    if sys.version_info >= (3,):
        @classmethod
        def FromString(cls, s: builtin___bytes) -> Version: ...
    else:
        @classmethod
        def FromString(cls, s: typing___Union[builtin___bytes, builtin___buffer, builtin___unicode]) -> Version: ...
    def MergeFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def CopyFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    if sys.version_info >= (3,):
        def HasField(self, field_name: typing_extensions___Literal[u"os",u"os_version",u"release",u"version"]) -> builtin___bool: ...
        def ClearField(self, field_name: typing_extensions___Literal[u"os",u"os_version",u"release",u"version"]) -> None: ...
    else:
        def HasField(self, field_name: typing_extensions___Literal[u"os",b"os",u"os_version",b"os_version",u"release",b"release",u"version",b"version"]) -> builtin___bool: ...
        def ClearField(self, field_name: typing_extensions___Literal[u"os",b"os",u"os_version",b"os_version",u"release",b"release",u"version",b"version"]) -> None: ...

class UDPTunnel(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    packet = ... # type: builtin___bytes

    def __init__(self,
        *,
        packet : builtin___bytes,
        ) -> None: ...
    if sys.version_info >= (3,):
        @classmethod
        def FromString(cls, s: builtin___bytes) -> UDPTunnel: ...
    else:
        @classmethod
        def FromString(cls, s: typing___Union[builtin___bytes, builtin___buffer, builtin___unicode]) -> UDPTunnel: ...
    def MergeFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def CopyFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    if sys.version_info >= (3,):
        def HasField(self, field_name: typing_extensions___Literal[u"packet"]) -> builtin___bool: ...
        def ClearField(self, field_name: typing_extensions___Literal[u"packet"]) -> None: ...
    else:
        def HasField(self, field_name: typing_extensions___Literal[u"packet",b"packet"]) -> builtin___bool: ...
        def ClearField(self, field_name: typing_extensions___Literal[u"packet",b"packet"]) -> None: ...

class Authenticate(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    username = ... # type: typing___Text
    password = ... # type: typing___Text
    tokens = ... # type: google___protobuf___internal___containers___RepeatedScalarFieldContainer[typing___Text]
    celt_versions = ... # type: google___protobuf___internal___containers___RepeatedScalarFieldContainer[builtin___int]
    opus = ... # type: builtin___bool

    def __init__(self,
        *,
        username : typing___Optional[typing___Text] = None,
        password : typing___Optional[typing___Text] = None,
        tokens : typing___Optional[typing___Iterable[typing___Text]] = None,
        celt_versions : typing___Optional[typing___Iterable[builtin___int]] = None,
        opus : typing___Optional[builtin___bool] = None,
        ) -> None: ...
    if sys.version_info >= (3,):
        @classmethod
        def FromString(cls, s: builtin___bytes) -> Authenticate: ...
    else:
        @classmethod
        def FromString(cls, s: typing___Union[builtin___bytes, builtin___buffer, builtin___unicode]) -> Authenticate: ...
    def MergeFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def CopyFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    if sys.version_info >= (3,):
        def HasField(self, field_name: typing_extensions___Literal[u"opus",u"password",u"username"]) -> builtin___bool: ...
        def ClearField(self, field_name: typing_extensions___Literal[u"celt_versions",u"opus",u"password",u"tokens",u"username"]) -> None: ...
    else:
        def HasField(self, field_name: typing_extensions___Literal[u"opus",b"opus",u"password",b"password",u"username",b"username"]) -> builtin___bool: ...
        def ClearField(self, field_name: typing_extensions___Literal[u"celt_versions",b"celt_versions",u"opus",b"opus",u"password",b"password",u"tokens",b"tokens",u"username",b"username"]) -> None: ...

class Ping(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    timestamp = ... # type: builtin___int
    good = ... # type: builtin___int
    late = ... # type: builtin___int
    lost = ... # type: builtin___int
    resync = ... # type: builtin___int
    udp_packets = ... # type: builtin___int
    tcp_packets = ... # type: builtin___int
    udp_ping_avg = ... # type: builtin___float
    udp_ping_var = ... # type: builtin___float
    tcp_ping_avg = ... # type: builtin___float
    tcp_ping_var = ... # type: builtin___float

    def __init__(self,
        *,
        timestamp : typing___Optional[builtin___int] = None,
        good : typing___Optional[builtin___int] = None,
        late : typing___Optional[builtin___int] = None,
        lost : typing___Optional[builtin___int] = None,
        resync : typing___Optional[builtin___int] = None,
        udp_packets : typing___Optional[builtin___int] = None,
        tcp_packets : typing___Optional[builtin___int] = None,
        udp_ping_avg : typing___Optional[builtin___float] = None,
        udp_ping_var : typing___Optional[builtin___float] = None,
        tcp_ping_avg : typing___Optional[builtin___float] = None,
        tcp_ping_var : typing___Optional[builtin___float] = None,
        ) -> None: ...
    if sys.version_info >= (3,):
        @classmethod
        def FromString(cls, s: builtin___bytes) -> Ping: ...
    else:
        @classmethod
        def FromString(cls, s: typing___Union[builtin___bytes, builtin___buffer, builtin___unicode]) -> Ping: ...
    def MergeFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def CopyFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    if sys.version_info >= (3,):
        def HasField(self, field_name: typing_extensions___Literal[u"good",u"late",u"lost",u"resync",u"tcp_packets",u"tcp_ping_avg",u"tcp_ping_var",u"timestamp",u"udp_packets",u"udp_ping_avg",u"udp_ping_var"]) -> builtin___bool: ...
        def ClearField(self, field_name: typing_extensions___Literal[u"good",u"late",u"lost",u"resync",u"tcp_packets",u"tcp_ping_avg",u"tcp_ping_var",u"timestamp",u"udp_packets",u"udp_ping_avg",u"udp_ping_var"]) -> None: ...
    else:
        def HasField(self, field_name: typing_extensions___Literal[u"good",b"good",u"late",b"late",u"lost",b"lost",u"resync",b"resync",u"tcp_packets",b"tcp_packets",u"tcp_ping_avg",b"tcp_ping_avg",u"tcp_ping_var",b"tcp_ping_var",u"timestamp",b"timestamp",u"udp_packets",b"udp_packets",u"udp_ping_avg",b"udp_ping_avg",u"udp_ping_var",b"udp_ping_var"]) -> builtin___bool: ...
        def ClearField(self, field_name: typing_extensions___Literal[u"good",b"good",u"late",b"late",u"lost",b"lost",u"resync",b"resync",u"tcp_packets",b"tcp_packets",u"tcp_ping_avg",b"tcp_ping_avg",u"tcp_ping_var",b"tcp_ping_var",u"timestamp",b"timestamp",u"udp_packets",b"udp_packets",u"udp_ping_avg",b"udp_ping_avg",u"udp_ping_var",b"udp_ping_var"]) -> None: ...

class Reject(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    class RejectType(builtin___int):
        DESCRIPTOR: google___protobuf___descriptor___EnumDescriptor = ...
        @classmethod
        def Name(cls, number: builtin___int) -> builtin___str: ...
        @classmethod
        def Value(cls, name: builtin___str) -> 'Reject.RejectType': ...
        @classmethod
        def keys(cls) -> typing___List[builtin___str]: ...
        @classmethod
        def values(cls) -> typing___List['Reject.RejectType']: ...
        @classmethod
        def items(cls) -> typing___List[typing___Tuple[builtin___str, 'Reject.RejectType']]: ...
        WrongVersion = typing___cast('Reject.RejectType', 1)
        InvalidUsername = typing___cast('Reject.RejectType', 2)
        WrongUserPW = typing___cast('Reject.RejectType', 3)
        WrongServerPW = typing___cast('Reject.RejectType', 4)
        UsernameInUse = typing___cast('Reject.RejectType', 5)
        ServerFull = typing___cast('Reject.RejectType', 6)
        NoCertificate = typing___cast('Reject.RejectType', 7)
        AuthenticatorFail = typing___cast('Reject.RejectType', 8)
    WrongVersion = typing___cast('Reject.RejectType', 1)
    InvalidUsername = typing___cast('Reject.RejectType', 2)
    WrongUserPW = typing___cast('Reject.RejectType', 3)
    WrongServerPW = typing___cast('Reject.RejectType', 4)
    UsernameInUse = typing___cast('Reject.RejectType', 5)
    ServerFull = typing___cast('Reject.RejectType', 6)
    NoCertificate = typing___cast('Reject.RejectType', 7)
    AuthenticatorFail = typing___cast('Reject.RejectType', 8)

    type = ... # type: Reject.RejectType
    reason = ... # type: typing___Text

    def __init__(self,
        *,
        type : typing___Optional[Reject.RejectType] = None,
        reason : typing___Optional[typing___Text] = None,
        ) -> None: ...
    if sys.version_info >= (3,):
        @classmethod
        def FromString(cls, s: builtin___bytes) -> Reject: ...
    else:
        @classmethod
        def FromString(cls, s: typing___Union[builtin___bytes, builtin___buffer, builtin___unicode]) -> Reject: ...
    def MergeFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def CopyFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    if sys.version_info >= (3,):
        def HasField(self, field_name: typing_extensions___Literal[u"reason",u"type"]) -> builtin___bool: ...
        def ClearField(self, field_name: typing_extensions___Literal[u"reason",u"type"]) -> None: ...
    else:
        def HasField(self, field_name: typing_extensions___Literal[u"reason",b"reason",u"type",b"type"]) -> builtin___bool: ...
        def ClearField(self, field_name: typing_extensions___Literal[u"reason",b"reason",u"type",b"type"]) -> None: ...

class ServerSync(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    session = ... # type: builtin___int
    max_bandwidth = ... # type: builtin___int
    welcome_text = ... # type: typing___Text
    permissions = ... # type: builtin___int

    def __init__(self,
        *,
        session : typing___Optional[builtin___int] = None,
        max_bandwidth : typing___Optional[builtin___int] = None,
        welcome_text : typing___Optional[typing___Text] = None,
        permissions : typing___Optional[builtin___int] = None,
        ) -> None: ...
    if sys.version_info >= (3,):
        @classmethod
        def FromString(cls, s: builtin___bytes) -> ServerSync: ...
    else:
        @classmethod
        def FromString(cls, s: typing___Union[builtin___bytes, builtin___buffer, builtin___unicode]) -> ServerSync: ...
    def MergeFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def CopyFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    if sys.version_info >= (3,):
        def HasField(self, field_name: typing_extensions___Literal[u"max_bandwidth",u"permissions",u"session",u"welcome_text"]) -> builtin___bool: ...
        def ClearField(self, field_name: typing_extensions___Literal[u"max_bandwidth",u"permissions",u"session",u"welcome_text"]) -> None: ...
    else:
        def HasField(self, field_name: typing_extensions___Literal[u"max_bandwidth",b"max_bandwidth",u"permissions",b"permissions",u"session",b"session",u"welcome_text",b"welcome_text"]) -> builtin___bool: ...
        def ClearField(self, field_name: typing_extensions___Literal[u"max_bandwidth",b"max_bandwidth",u"permissions",b"permissions",u"session",b"session",u"welcome_text",b"welcome_text"]) -> None: ...

class ChannelRemove(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    channel_id = ... # type: builtin___int

    def __init__(self,
        *,
        channel_id : builtin___int,
        ) -> None: ...
    if sys.version_info >= (3,):
        @classmethod
        def FromString(cls, s: builtin___bytes) -> ChannelRemove: ...
    else:
        @classmethod
        def FromString(cls, s: typing___Union[builtin___bytes, builtin___buffer, builtin___unicode]) -> ChannelRemove: ...
    def MergeFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def CopyFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    if sys.version_info >= (3,):
        def HasField(self, field_name: typing_extensions___Literal[u"channel_id"]) -> builtin___bool: ...
        def ClearField(self, field_name: typing_extensions___Literal[u"channel_id"]) -> None: ...
    else:
        def HasField(self, field_name: typing_extensions___Literal[u"channel_id",b"channel_id"]) -> builtin___bool: ...
        def ClearField(self, field_name: typing_extensions___Literal[u"channel_id",b"channel_id"]) -> None: ...

class ChannelState(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    channel_id = ... # type: builtin___int
    parent = ... # type: builtin___int
    name = ... # type: typing___Text
    links = ... # type: google___protobuf___internal___containers___RepeatedScalarFieldContainer[builtin___int]
    description = ... # type: typing___Text
    links_add = ... # type: google___protobuf___internal___containers___RepeatedScalarFieldContainer[builtin___int]
    links_remove = ... # type: google___protobuf___internal___containers___RepeatedScalarFieldContainer[builtin___int]
    temporary = ... # type: builtin___bool
    position = ... # type: builtin___int
    description_hash = ... # type: builtin___bytes
    max_users = ... # type: builtin___int

    def __init__(self,
        *,
        channel_id : typing___Optional[builtin___int] = None,
        parent : typing___Optional[builtin___int] = None,
        name : typing___Optional[typing___Text] = None,
        links : typing___Optional[typing___Iterable[builtin___int]] = None,
        description : typing___Optional[typing___Text] = None,
        links_add : typing___Optional[typing___Iterable[builtin___int]] = None,
        links_remove : typing___Optional[typing___Iterable[builtin___int]] = None,
        temporary : typing___Optional[builtin___bool] = None,
        position : typing___Optional[builtin___int] = None,
        description_hash : typing___Optional[builtin___bytes] = None,
        max_users : typing___Optional[builtin___int] = None,
        ) -> None: ...
    if sys.version_info >= (3,):
        @classmethod
        def FromString(cls, s: builtin___bytes) -> ChannelState: ...
    else:
        @classmethod
        def FromString(cls, s: typing___Union[builtin___bytes, builtin___buffer, builtin___unicode]) -> ChannelState: ...
    def MergeFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def CopyFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    if sys.version_info >= (3,):
        def HasField(self, field_name: typing_extensions___Literal[u"channel_id",u"description",u"description_hash",u"max_users",u"name",u"parent",u"position",u"temporary"]) -> builtin___bool: ...
        def ClearField(self, field_name: typing_extensions___Literal[u"channel_id",u"description",u"description_hash",u"links",u"links_add",u"links_remove",u"max_users",u"name",u"parent",u"position",u"temporary"]) -> None: ...
    else:
        def HasField(self, field_name: typing_extensions___Literal[u"channel_id",b"channel_id",u"description",b"description",u"description_hash",b"description_hash",u"max_users",b"max_users",u"name",b"name",u"parent",b"parent",u"position",b"position",u"temporary",b"temporary"]) -> builtin___bool: ...
        def ClearField(self, field_name: typing_extensions___Literal[u"channel_id",b"channel_id",u"description",b"description",u"description_hash",b"description_hash",u"links",b"links",u"links_add",b"links_add",u"links_remove",b"links_remove",u"max_users",b"max_users",u"name",b"name",u"parent",b"parent",u"position",b"position",u"temporary",b"temporary"]) -> None: ...

class UserRemove(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    session = ... # type: builtin___int
    actor = ... # type: builtin___int
    reason = ... # type: typing___Text
    ban = ... # type: builtin___bool

    def __init__(self,
        *,
        session : builtin___int,
        actor : typing___Optional[builtin___int] = None,
        reason : typing___Optional[typing___Text] = None,
        ban : typing___Optional[builtin___bool] = None,
        ) -> None: ...
    if sys.version_info >= (3,):
        @classmethod
        def FromString(cls, s: builtin___bytes) -> UserRemove: ...
    else:
        @classmethod
        def FromString(cls, s: typing___Union[builtin___bytes, builtin___buffer, builtin___unicode]) -> UserRemove: ...
    def MergeFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def CopyFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    if sys.version_info >= (3,):
        def HasField(self, field_name: typing_extensions___Literal[u"actor",u"ban",u"reason",u"session"]) -> builtin___bool: ...
        def ClearField(self, field_name: typing_extensions___Literal[u"actor",u"ban",u"reason",u"session"]) -> None: ...
    else:
        def HasField(self, field_name: typing_extensions___Literal[u"actor",b"actor",u"ban",b"ban",u"reason",b"reason",u"session",b"session"]) -> builtin___bool: ...
        def ClearField(self, field_name: typing_extensions___Literal[u"actor",b"actor",u"ban",b"ban",u"reason",b"reason",u"session",b"session"]) -> None: ...

class UserState(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    session = ... # type: builtin___int
    actor = ... # type: builtin___int
    name = ... # type: typing___Text
    user_id = ... # type: builtin___int
    channel_id = ... # type: builtin___int
    mute = ... # type: builtin___bool
    deaf = ... # type: builtin___bool
    suppress = ... # type: builtin___bool
    self_mute = ... # type: builtin___bool
    self_deaf = ... # type: builtin___bool
    texture = ... # type: builtin___bytes
    plugin_context = ... # type: builtin___bytes
    plugin_identity = ... # type: typing___Text
    comment = ... # type: typing___Text
    hash = ... # type: typing___Text
    comment_hash = ... # type: builtin___bytes
    texture_hash = ... # type: builtin___bytes
    priority_speaker = ... # type: builtin___bool
    recording = ... # type: builtin___bool

    def __init__(self,
        *,
        session : typing___Optional[builtin___int] = None,
        actor : typing___Optional[builtin___int] = None,
        name : typing___Optional[typing___Text] = None,
        user_id : typing___Optional[builtin___int] = None,
        channel_id : typing___Optional[builtin___int] = None,
        mute : typing___Optional[builtin___bool] = None,
        deaf : typing___Optional[builtin___bool] = None,
        suppress : typing___Optional[builtin___bool] = None,
        self_mute : typing___Optional[builtin___bool] = None,
        self_deaf : typing___Optional[builtin___bool] = None,
        texture : typing___Optional[builtin___bytes] = None,
        plugin_context : typing___Optional[builtin___bytes] = None,
        plugin_identity : typing___Optional[typing___Text] = None,
        comment : typing___Optional[typing___Text] = None,
        hash : typing___Optional[typing___Text] = None,
        comment_hash : typing___Optional[builtin___bytes] = None,
        texture_hash : typing___Optional[builtin___bytes] = None,
        priority_speaker : typing___Optional[builtin___bool] = None,
        recording : typing___Optional[builtin___bool] = None,
        ) -> None: ...
    if sys.version_info >= (3,):
        @classmethod
        def FromString(cls, s: builtin___bytes) -> UserState: ...
    else:
        @classmethod
        def FromString(cls, s: typing___Union[builtin___bytes, builtin___buffer, builtin___unicode]) -> UserState: ...
    def MergeFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def CopyFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    if sys.version_info >= (3,):
        def HasField(self, field_name: typing_extensions___Literal[u"actor",u"channel_id",u"comment",u"comment_hash",u"deaf",u"hash",u"mute",u"name",u"plugin_context",u"plugin_identity",u"priority_speaker",u"recording",u"self_deaf",u"self_mute",u"session",u"suppress",u"texture",u"texture_hash",u"user_id"]) -> builtin___bool: ...
        def ClearField(self, field_name: typing_extensions___Literal[u"actor",u"channel_id",u"comment",u"comment_hash",u"deaf",u"hash",u"mute",u"name",u"plugin_context",u"plugin_identity",u"priority_speaker",u"recording",u"self_deaf",u"self_mute",u"session",u"suppress",u"texture",u"texture_hash",u"user_id"]) -> None: ...
    else:
        def HasField(self, field_name: typing_extensions___Literal[u"actor",b"actor",u"channel_id",b"channel_id",u"comment",b"comment",u"comment_hash",b"comment_hash",u"deaf",b"deaf",u"hash",b"hash",u"mute",b"mute",u"name",b"name",u"plugin_context",b"plugin_context",u"plugin_identity",b"plugin_identity",u"priority_speaker",b"priority_speaker",u"recording",b"recording",u"self_deaf",b"self_deaf",u"self_mute",b"self_mute",u"session",b"session",u"suppress",b"suppress",u"texture",b"texture",u"texture_hash",b"texture_hash",u"user_id",b"user_id"]) -> builtin___bool: ...
        def ClearField(self, field_name: typing_extensions___Literal[u"actor",b"actor",u"channel_id",b"channel_id",u"comment",b"comment",u"comment_hash",b"comment_hash",u"deaf",b"deaf",u"hash",b"hash",u"mute",b"mute",u"name",b"name",u"plugin_context",b"plugin_context",u"plugin_identity",b"plugin_identity",u"priority_speaker",b"priority_speaker",u"recording",b"recording",u"self_deaf",b"self_deaf",u"self_mute",b"self_mute",u"session",b"session",u"suppress",b"suppress",u"texture",b"texture",u"texture_hash",b"texture_hash",u"user_id",b"user_id"]) -> None: ...

class BanList(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    class BanEntry(google___protobuf___message___Message):
        DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
        address = ... # type: builtin___bytes
        mask = ... # type: builtin___int
        name = ... # type: typing___Text
        hash = ... # type: typing___Text
        reason = ... # type: typing___Text
        start = ... # type: typing___Text
        duration = ... # type: builtin___int

        def __init__(self,
            *,
            address : builtin___bytes,
            mask : builtin___int,
            name : typing___Optional[typing___Text] = None,
            hash : typing___Optional[typing___Text] = None,
            reason : typing___Optional[typing___Text] = None,
            start : typing___Optional[typing___Text] = None,
            duration : typing___Optional[builtin___int] = None,
            ) -> None: ...
        if sys.version_info >= (3,):
            @classmethod
            def FromString(cls, s: builtin___bytes) -> BanList.BanEntry: ...
        else:
            @classmethod
            def FromString(cls, s: typing___Union[builtin___bytes, builtin___buffer, builtin___unicode]) -> BanList.BanEntry: ...
        def MergeFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
        def CopyFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
        if sys.version_info >= (3,):
            def HasField(self, field_name: typing_extensions___Literal[u"address",u"duration",u"hash",u"mask",u"name",u"reason",u"start"]) -> builtin___bool: ...
            def ClearField(self, field_name: typing_extensions___Literal[u"address",u"duration",u"hash",u"mask",u"name",u"reason",u"start"]) -> None: ...
        else:
            def HasField(self, field_name: typing_extensions___Literal[u"address",b"address",u"duration",b"duration",u"hash",b"hash",u"mask",b"mask",u"name",b"name",u"reason",b"reason",u"start",b"start"]) -> builtin___bool: ...
            def ClearField(self, field_name: typing_extensions___Literal[u"address",b"address",u"duration",b"duration",u"hash",b"hash",u"mask",b"mask",u"name",b"name",u"reason",b"reason",u"start",b"start"]) -> None: ...

    query = ... # type: builtin___bool

    @property
    def bans(self) -> google___protobuf___internal___containers___RepeatedCompositeFieldContainer[BanList.BanEntry]: ...

    def __init__(self,
        *,
        bans : typing___Optional[typing___Iterable[BanList.BanEntry]] = None,
        query : typing___Optional[builtin___bool] = None,
        ) -> None: ...
    if sys.version_info >= (3,):
        @classmethod
        def FromString(cls, s: builtin___bytes) -> BanList: ...
    else:
        @classmethod
        def FromString(cls, s: typing___Union[builtin___bytes, builtin___buffer, builtin___unicode]) -> BanList: ...
    def MergeFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def CopyFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    if sys.version_info >= (3,):
        def HasField(self, field_name: typing_extensions___Literal[u"query"]) -> builtin___bool: ...
        def ClearField(self, field_name: typing_extensions___Literal[u"bans",u"query"]) -> None: ...
    else:
        def HasField(self, field_name: typing_extensions___Literal[u"query",b"query"]) -> builtin___bool: ...
        def ClearField(self, field_name: typing_extensions___Literal[u"bans",b"bans",u"query",b"query"]) -> None: ...

class TextMessage(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    actor = ... # type: builtin___int
    session = ... # type: google___protobuf___internal___containers___RepeatedScalarFieldContainer[builtin___int]
    channel_id = ... # type: google___protobuf___internal___containers___RepeatedScalarFieldContainer[builtin___int]
    tree_id = ... # type: google___protobuf___internal___containers___RepeatedScalarFieldContainer[builtin___int]
    message = ... # type: typing___Text

    def __init__(self,
        *,
        message : typing___Text,
        actor : typing___Optional[builtin___int] = None,
        session : typing___Optional[typing___Iterable[builtin___int]] = None,
        channel_id : typing___Optional[typing___Iterable[builtin___int]] = None,
        tree_id : typing___Optional[typing___Iterable[builtin___int]] = None,
        ) -> None: ...
    if sys.version_info >= (3,):
        @classmethod
        def FromString(cls, s: builtin___bytes) -> TextMessage: ...
    else:
        @classmethod
        def FromString(cls, s: typing___Union[builtin___bytes, builtin___buffer, builtin___unicode]) -> TextMessage: ...
    def MergeFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def CopyFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    if sys.version_info >= (3,):
        def HasField(self, field_name: typing_extensions___Literal[u"actor",u"message"]) -> builtin___bool: ...
        def ClearField(self, field_name: typing_extensions___Literal[u"actor",u"channel_id",u"message",u"session",u"tree_id"]) -> None: ...
    else:
        def HasField(self, field_name: typing_extensions___Literal[u"actor",b"actor",u"message",b"message"]) -> builtin___bool: ...
        def ClearField(self, field_name: typing_extensions___Literal[u"actor",b"actor",u"channel_id",b"channel_id",u"message",b"message",u"session",b"session",u"tree_id",b"tree_id"]) -> None: ...

class PermissionDenied(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    class DenyType(builtin___int):
        DESCRIPTOR: google___protobuf___descriptor___EnumDescriptor = ...
        @classmethod
        def Name(cls, number: builtin___int) -> builtin___str: ...
        @classmethod
        def Value(cls, name: builtin___str) -> 'PermissionDenied.DenyType': ...
        @classmethod
        def keys(cls) -> typing___List[builtin___str]: ...
        @classmethod
        def values(cls) -> typing___List['PermissionDenied.DenyType']: ...
        @classmethod
        def items(cls) -> typing___List[typing___Tuple[builtin___str, 'PermissionDenied.DenyType']]: ...
        Text = typing___cast('PermissionDenied.DenyType', 0)
        Permission = typing___cast('PermissionDenied.DenyType', 1)
        SuperUser = typing___cast('PermissionDenied.DenyType', 2)
        ChannelName = typing___cast('PermissionDenied.DenyType', 3)
        TextTooLong = typing___cast('PermissionDenied.DenyType', 4)
        H9K = typing___cast('PermissionDenied.DenyType', 5)
        TemporaryChannel = typing___cast('PermissionDenied.DenyType', 6)
        MissingCertificate = typing___cast('PermissionDenied.DenyType', 7)
        UserName = typing___cast('PermissionDenied.DenyType', 8)
        ChannelFull = typing___cast('PermissionDenied.DenyType', 9)
        NestingLimit = typing___cast('PermissionDenied.DenyType', 10)
        ChannelCountLimit = typing___cast('PermissionDenied.DenyType', 11)
    Text = typing___cast('PermissionDenied.DenyType', 0)
    Permission = typing___cast('PermissionDenied.DenyType', 1)
    SuperUser = typing___cast('PermissionDenied.DenyType', 2)
    ChannelName = typing___cast('PermissionDenied.DenyType', 3)
    TextTooLong = typing___cast('PermissionDenied.DenyType', 4)
    H9K = typing___cast('PermissionDenied.DenyType', 5)
    TemporaryChannel = typing___cast('PermissionDenied.DenyType', 6)
    MissingCertificate = typing___cast('PermissionDenied.DenyType', 7)
    UserName = typing___cast('PermissionDenied.DenyType', 8)
    ChannelFull = typing___cast('PermissionDenied.DenyType', 9)
    NestingLimit = typing___cast('PermissionDenied.DenyType', 10)
    ChannelCountLimit = typing___cast('PermissionDenied.DenyType', 11)

    permission = ... # type: builtin___int
    channel_id = ... # type: builtin___int
    session = ... # type: builtin___int
    reason = ... # type: typing___Text
    type = ... # type: PermissionDenied.DenyType
    name = ... # type: typing___Text

    def __init__(self,
        *,
        permission : typing___Optional[builtin___int] = None,
        channel_id : typing___Optional[builtin___int] = None,
        session : typing___Optional[builtin___int] = None,
        reason : typing___Optional[typing___Text] = None,
        type : typing___Optional[PermissionDenied.DenyType] = None,
        name : typing___Optional[typing___Text] = None,
        ) -> None: ...
    if sys.version_info >= (3,):
        @classmethod
        def FromString(cls, s: builtin___bytes) -> PermissionDenied: ...
    else:
        @classmethod
        def FromString(cls, s: typing___Union[builtin___bytes, builtin___buffer, builtin___unicode]) -> PermissionDenied: ...
    def MergeFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def CopyFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    if sys.version_info >= (3,):
        def HasField(self, field_name: typing_extensions___Literal[u"channel_id",u"name",u"permission",u"reason",u"session",u"type"]) -> builtin___bool: ...
        def ClearField(self, field_name: typing_extensions___Literal[u"channel_id",u"name",u"permission",u"reason",u"session",u"type"]) -> None: ...
    else:
        def HasField(self, field_name: typing_extensions___Literal[u"channel_id",b"channel_id",u"name",b"name",u"permission",b"permission",u"reason",b"reason",u"session",b"session",u"type",b"type"]) -> builtin___bool: ...
        def ClearField(self, field_name: typing_extensions___Literal[u"channel_id",b"channel_id",u"name",b"name",u"permission",b"permission",u"reason",b"reason",u"session",b"session",u"type",b"type"]) -> None: ...

class ACL(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    class ChanGroup(google___protobuf___message___Message):
        DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
        name = ... # type: typing___Text
        inherited = ... # type: builtin___bool
        inherit = ... # type: builtin___bool
        inheritable = ... # type: builtin___bool
        add = ... # type: google___protobuf___internal___containers___RepeatedScalarFieldContainer[builtin___int]
        remove = ... # type: google___protobuf___internal___containers___RepeatedScalarFieldContainer[builtin___int]
        inherited_members = ... # type: google___protobuf___internal___containers___RepeatedScalarFieldContainer[builtin___int]

        def __init__(self,
            *,
            name : typing___Text,
            inherited : typing___Optional[builtin___bool] = None,
            inherit : typing___Optional[builtin___bool] = None,
            inheritable : typing___Optional[builtin___bool] = None,
            add : typing___Optional[typing___Iterable[builtin___int]] = None,
            remove : typing___Optional[typing___Iterable[builtin___int]] = None,
            inherited_members : typing___Optional[typing___Iterable[builtin___int]] = None,
            ) -> None: ...
        if sys.version_info >= (3,):
            @classmethod
            def FromString(cls, s: builtin___bytes) -> ACL.ChanGroup: ...
        else:
            @classmethod
            def FromString(cls, s: typing___Union[builtin___bytes, builtin___buffer, builtin___unicode]) -> ACL.ChanGroup: ...
        def MergeFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
        def CopyFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
        if sys.version_info >= (3,):
            def HasField(self, field_name: typing_extensions___Literal[u"inherit",u"inheritable",u"inherited",u"name"]) -> builtin___bool: ...
            def ClearField(self, field_name: typing_extensions___Literal[u"add",u"inherit",u"inheritable",u"inherited",u"inherited_members",u"name",u"remove"]) -> None: ...
        else:
            def HasField(self, field_name: typing_extensions___Literal[u"inherit",b"inherit",u"inheritable",b"inheritable",u"inherited",b"inherited",u"name",b"name"]) -> builtin___bool: ...
            def ClearField(self, field_name: typing_extensions___Literal[u"add",b"add",u"inherit",b"inherit",u"inheritable",b"inheritable",u"inherited",b"inherited",u"inherited_members",b"inherited_members",u"name",b"name",u"remove",b"remove"]) -> None: ...

    class ChanACL(google___protobuf___message___Message):
        DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
        apply_here = ... # type: builtin___bool
        apply_subs = ... # type: builtin___bool
        inherited = ... # type: builtin___bool
        user_id = ... # type: builtin___int
        group = ... # type: typing___Text
        grant = ... # type: builtin___int
        deny = ... # type: builtin___int

        def __init__(self,
            *,
            apply_here : typing___Optional[builtin___bool] = None,
            apply_subs : typing___Optional[builtin___bool] = None,
            inherited : typing___Optional[builtin___bool] = None,
            user_id : typing___Optional[builtin___int] = None,
            group : typing___Optional[typing___Text] = None,
            grant : typing___Optional[builtin___int] = None,
            deny : typing___Optional[builtin___int] = None,
            ) -> None: ...
        if sys.version_info >= (3,):
            @classmethod
            def FromString(cls, s: builtin___bytes) -> ACL.ChanACL: ...
        else:
            @classmethod
            def FromString(cls, s: typing___Union[builtin___bytes, builtin___buffer, builtin___unicode]) -> ACL.ChanACL: ...
        def MergeFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
        def CopyFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
        if sys.version_info >= (3,):
            def HasField(self, field_name: typing_extensions___Literal[u"apply_here",u"apply_subs",u"deny",u"grant",u"group",u"inherited",u"user_id"]) -> builtin___bool: ...
            def ClearField(self, field_name: typing_extensions___Literal[u"apply_here",u"apply_subs",u"deny",u"grant",u"group",u"inherited",u"user_id"]) -> None: ...
        else:
            def HasField(self, field_name: typing_extensions___Literal[u"apply_here",b"apply_here",u"apply_subs",b"apply_subs",u"deny",b"deny",u"grant",b"grant",u"group",b"group",u"inherited",b"inherited",u"user_id",b"user_id"]) -> builtin___bool: ...
            def ClearField(self, field_name: typing_extensions___Literal[u"apply_here",b"apply_here",u"apply_subs",b"apply_subs",u"deny",b"deny",u"grant",b"grant",u"group",b"group",u"inherited",b"inherited",u"user_id",b"user_id"]) -> None: ...

    channel_id = ... # type: builtin___int
    inherit_acls = ... # type: builtin___bool
    query = ... # type: builtin___bool

    @property
    def groups(self) -> google___protobuf___internal___containers___RepeatedCompositeFieldContainer[ACL.ChanGroup]: ...

    @property
    def acls(self) -> google___protobuf___internal___containers___RepeatedCompositeFieldContainer[ACL.ChanACL]: ...

    def __init__(self,
        *,
        channel_id : builtin___int,
        inherit_acls : typing___Optional[builtin___bool] = None,
        groups : typing___Optional[typing___Iterable[ACL.ChanGroup]] = None,
        acls : typing___Optional[typing___Iterable[ACL.ChanACL]] = None,
        query : typing___Optional[builtin___bool] = None,
        ) -> None: ...
    if sys.version_info >= (3,):
        @classmethod
        def FromString(cls, s: builtin___bytes) -> ACL: ...
    else:
        @classmethod
        def FromString(cls, s: typing___Union[builtin___bytes, builtin___buffer, builtin___unicode]) -> ACL: ...
    def MergeFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def CopyFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    if sys.version_info >= (3,):
        def HasField(self, field_name: typing_extensions___Literal[u"channel_id",u"inherit_acls",u"query"]) -> builtin___bool: ...
        def ClearField(self, field_name: typing_extensions___Literal[u"acls",u"channel_id",u"groups",u"inherit_acls",u"query"]) -> None: ...
    else:
        def HasField(self, field_name: typing_extensions___Literal[u"channel_id",b"channel_id",u"inherit_acls",b"inherit_acls",u"query",b"query"]) -> builtin___bool: ...
        def ClearField(self, field_name: typing_extensions___Literal[u"acls",b"acls",u"channel_id",b"channel_id",u"groups",b"groups",u"inherit_acls",b"inherit_acls",u"query",b"query"]) -> None: ...

class QueryUsers(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    ids = ... # type: google___protobuf___internal___containers___RepeatedScalarFieldContainer[builtin___int]
    names = ... # type: google___protobuf___internal___containers___RepeatedScalarFieldContainer[typing___Text]

    def __init__(self,
        *,
        ids : typing___Optional[typing___Iterable[builtin___int]] = None,
        names : typing___Optional[typing___Iterable[typing___Text]] = None,
        ) -> None: ...
    if sys.version_info >= (3,):
        @classmethod
        def FromString(cls, s: builtin___bytes) -> QueryUsers: ...
    else:
        @classmethod
        def FromString(cls, s: typing___Union[builtin___bytes, builtin___buffer, builtin___unicode]) -> QueryUsers: ...
    def MergeFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def CopyFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    if sys.version_info >= (3,):
        def ClearField(self, field_name: typing_extensions___Literal[u"ids",u"names"]) -> None: ...
    else:
        def ClearField(self, field_name: typing_extensions___Literal[u"ids",b"ids",u"names",b"names"]) -> None: ...

class CryptSetup(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    key = ... # type: builtin___bytes
    client_nonce = ... # type: builtin___bytes
    server_nonce = ... # type: builtin___bytes

    def __init__(self,
        *,
        key : typing___Optional[builtin___bytes] = None,
        client_nonce : typing___Optional[builtin___bytes] = None,
        server_nonce : typing___Optional[builtin___bytes] = None,
        ) -> None: ...
    if sys.version_info >= (3,):
        @classmethod
        def FromString(cls, s: builtin___bytes) -> CryptSetup: ...
    else:
        @classmethod
        def FromString(cls, s: typing___Union[builtin___bytes, builtin___buffer, builtin___unicode]) -> CryptSetup: ...
    def MergeFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def CopyFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    if sys.version_info >= (3,):
        def HasField(self, field_name: typing_extensions___Literal[u"client_nonce",u"key",u"server_nonce"]) -> builtin___bool: ...
        def ClearField(self, field_name: typing_extensions___Literal[u"client_nonce",u"key",u"server_nonce"]) -> None: ...
    else:
        def HasField(self, field_name: typing_extensions___Literal[u"client_nonce",b"client_nonce",u"key",b"key",u"server_nonce",b"server_nonce"]) -> builtin___bool: ...
        def ClearField(self, field_name: typing_extensions___Literal[u"client_nonce",b"client_nonce",u"key",b"key",u"server_nonce",b"server_nonce"]) -> None: ...

class ContextActionModify(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    class Context(builtin___int):
        DESCRIPTOR: google___protobuf___descriptor___EnumDescriptor = ...
        @classmethod
        def Name(cls, number: builtin___int) -> builtin___str: ...
        @classmethod
        def Value(cls, name: builtin___str) -> 'ContextActionModify.Context': ...
        @classmethod
        def keys(cls) -> typing___List[builtin___str]: ...
        @classmethod
        def values(cls) -> typing___List['ContextActionModify.Context']: ...
        @classmethod
        def items(cls) -> typing___List[typing___Tuple[builtin___str, 'ContextActionModify.Context']]: ...
        Server = typing___cast('ContextActionModify.Context', 1)
        Channel = typing___cast('ContextActionModify.Context', 2)
        User = typing___cast('ContextActionModify.Context', 4)
    Server = typing___cast('ContextActionModify.Context', 1)
    Channel = typing___cast('ContextActionModify.Context', 2)
    User = typing___cast('ContextActionModify.Context', 4)

    class Operation(builtin___int):
        DESCRIPTOR: google___protobuf___descriptor___EnumDescriptor = ...
        @classmethod
        def Name(cls, number: builtin___int) -> builtin___str: ...
        @classmethod
        def Value(cls, name: builtin___str) -> 'ContextActionModify.Operation': ...
        @classmethod
        def keys(cls) -> typing___List[builtin___str]: ...
        @classmethod
        def values(cls) -> typing___List['ContextActionModify.Operation']: ...
        @classmethod
        def items(cls) -> typing___List[typing___Tuple[builtin___str, 'ContextActionModify.Operation']]: ...
        Add = typing___cast('ContextActionModify.Operation', 0)
        Remove = typing___cast('ContextActionModify.Operation', 1)
    Add = typing___cast('ContextActionModify.Operation', 0)
    Remove = typing___cast('ContextActionModify.Operation', 1)

    action = ... # type: typing___Text
    text = ... # type: typing___Text
    context = ... # type: builtin___int
    operation = ... # type: ContextActionModify.Operation

    def __init__(self,
        *,
        action : typing___Text,
        text : typing___Optional[typing___Text] = None,
        context : typing___Optional[builtin___int] = None,
        operation : typing___Optional[ContextActionModify.Operation] = None,
        ) -> None: ...
    if sys.version_info >= (3,):
        @classmethod
        def FromString(cls, s: builtin___bytes) -> ContextActionModify: ...
    else:
        @classmethod
        def FromString(cls, s: typing___Union[builtin___bytes, builtin___buffer, builtin___unicode]) -> ContextActionModify: ...
    def MergeFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def CopyFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    if sys.version_info >= (3,):
        def HasField(self, field_name: typing_extensions___Literal[u"action",u"context",u"operation",u"text"]) -> builtin___bool: ...
        def ClearField(self, field_name: typing_extensions___Literal[u"action",u"context",u"operation",u"text"]) -> None: ...
    else:
        def HasField(self, field_name: typing_extensions___Literal[u"action",b"action",u"context",b"context",u"operation",b"operation",u"text",b"text"]) -> builtin___bool: ...
        def ClearField(self, field_name: typing_extensions___Literal[u"action",b"action",u"context",b"context",u"operation",b"operation",u"text",b"text"]) -> None: ...

class ContextAction(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    session = ... # type: builtin___int
    channel_id = ... # type: builtin___int
    action = ... # type: typing___Text

    def __init__(self,
        *,
        action : typing___Text,
        session : typing___Optional[builtin___int] = None,
        channel_id : typing___Optional[builtin___int] = None,
        ) -> None: ...
    if sys.version_info >= (3,):
        @classmethod
        def FromString(cls, s: builtin___bytes) -> ContextAction: ...
    else:
        @classmethod
        def FromString(cls, s: typing___Union[builtin___bytes, builtin___buffer, builtin___unicode]) -> ContextAction: ...
    def MergeFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def CopyFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    if sys.version_info >= (3,):
        def HasField(self, field_name: typing_extensions___Literal[u"action",u"channel_id",u"session"]) -> builtin___bool: ...
        def ClearField(self, field_name: typing_extensions___Literal[u"action",u"channel_id",u"session"]) -> None: ...
    else:
        def HasField(self, field_name: typing_extensions___Literal[u"action",b"action",u"channel_id",b"channel_id",u"session",b"session"]) -> builtin___bool: ...
        def ClearField(self, field_name: typing_extensions___Literal[u"action",b"action",u"channel_id",b"channel_id",u"session",b"session"]) -> None: ...

class UserList(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    class User(google___protobuf___message___Message):
        DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
        user_id = ... # type: builtin___int
        name = ... # type: typing___Text
        last_seen = ... # type: typing___Text
        last_channel = ... # type: builtin___int

        def __init__(self,
            *,
            user_id : builtin___int,
            name : typing___Optional[typing___Text] = None,
            last_seen : typing___Optional[typing___Text] = None,
            last_channel : typing___Optional[builtin___int] = None,
            ) -> None: ...
        if sys.version_info >= (3,):
            @classmethod
            def FromString(cls, s: builtin___bytes) -> UserList.User: ...
        else:
            @classmethod
            def FromString(cls, s: typing___Union[builtin___bytes, builtin___buffer, builtin___unicode]) -> UserList.User: ...
        def MergeFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
        def CopyFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
        if sys.version_info >= (3,):
            def HasField(self, field_name: typing_extensions___Literal[u"last_channel",u"last_seen",u"name",u"user_id"]) -> builtin___bool: ...
            def ClearField(self, field_name: typing_extensions___Literal[u"last_channel",u"last_seen",u"name",u"user_id"]) -> None: ...
        else:
            def HasField(self, field_name: typing_extensions___Literal[u"last_channel",b"last_channel",u"last_seen",b"last_seen",u"name",b"name",u"user_id",b"user_id"]) -> builtin___bool: ...
            def ClearField(self, field_name: typing_extensions___Literal[u"last_channel",b"last_channel",u"last_seen",b"last_seen",u"name",b"name",u"user_id",b"user_id"]) -> None: ...


    @property
    def users(self) -> google___protobuf___internal___containers___RepeatedCompositeFieldContainer[UserList.User]: ...

    def __init__(self,
        *,
        users : typing___Optional[typing___Iterable[UserList.User]] = None,
        ) -> None: ...
    if sys.version_info >= (3,):
        @classmethod
        def FromString(cls, s: builtin___bytes) -> UserList: ...
    else:
        @classmethod
        def FromString(cls, s: typing___Union[builtin___bytes, builtin___buffer, builtin___unicode]) -> UserList: ...
    def MergeFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def CopyFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    if sys.version_info >= (3,):
        def ClearField(self, field_name: typing_extensions___Literal[u"users"]) -> None: ...
    else:
        def ClearField(self, field_name: typing_extensions___Literal[u"users",b"users"]) -> None: ...

class VoiceTarget(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    class Target(google___protobuf___message___Message):
        DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
        session = ... # type: google___protobuf___internal___containers___RepeatedScalarFieldContainer[builtin___int]
        channel_id = ... # type: builtin___int
        group = ... # type: typing___Text
        links = ... # type: builtin___bool
        children = ... # type: builtin___bool

        def __init__(self,
            *,
            session : typing___Optional[typing___Iterable[builtin___int]] = None,
            channel_id : typing___Optional[builtin___int] = None,
            group : typing___Optional[typing___Text] = None,
            links : typing___Optional[builtin___bool] = None,
            children : typing___Optional[builtin___bool] = None,
            ) -> None: ...
        if sys.version_info >= (3,):
            @classmethod
            def FromString(cls, s: builtin___bytes) -> VoiceTarget.Target: ...
        else:
            @classmethod
            def FromString(cls, s: typing___Union[builtin___bytes, builtin___buffer, builtin___unicode]) -> VoiceTarget.Target: ...
        def MergeFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
        def CopyFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
        if sys.version_info >= (3,):
            def HasField(self, field_name: typing_extensions___Literal[u"channel_id",u"children",u"group",u"links"]) -> builtin___bool: ...
            def ClearField(self, field_name: typing_extensions___Literal[u"channel_id",u"children",u"group",u"links",u"session"]) -> None: ...
        else:
            def HasField(self, field_name: typing_extensions___Literal[u"channel_id",b"channel_id",u"children",b"children",u"group",b"group",u"links",b"links"]) -> builtin___bool: ...
            def ClearField(self, field_name: typing_extensions___Literal[u"channel_id",b"channel_id",u"children",b"children",u"group",b"group",u"links",b"links",u"session",b"session"]) -> None: ...

    id = ... # type: builtin___int

    @property
    def targets(self) -> google___protobuf___internal___containers___RepeatedCompositeFieldContainer[VoiceTarget.Target]: ...

    def __init__(self,
        *,
        id : typing___Optional[builtin___int] = None,
        targets : typing___Optional[typing___Iterable[VoiceTarget.Target]] = None,
        ) -> None: ...
    if sys.version_info >= (3,):
        @classmethod
        def FromString(cls, s: builtin___bytes) -> VoiceTarget: ...
    else:
        @classmethod
        def FromString(cls, s: typing___Union[builtin___bytes, builtin___buffer, builtin___unicode]) -> VoiceTarget: ...
    def MergeFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def CopyFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    if sys.version_info >= (3,):
        def HasField(self, field_name: typing_extensions___Literal[u"id"]) -> builtin___bool: ...
        def ClearField(self, field_name: typing_extensions___Literal[u"id",u"targets"]) -> None: ...
    else:
        def HasField(self, field_name: typing_extensions___Literal[u"id",b"id"]) -> builtin___bool: ...
        def ClearField(self, field_name: typing_extensions___Literal[u"id",b"id",u"targets",b"targets"]) -> None: ...

class PermissionQuery(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    channel_id = ... # type: builtin___int
    permissions = ... # type: builtin___int
    flush = ... # type: builtin___bool

    def __init__(self,
        *,
        channel_id : typing___Optional[builtin___int] = None,
        permissions : typing___Optional[builtin___int] = None,
        flush : typing___Optional[builtin___bool] = None,
        ) -> None: ...
    if sys.version_info >= (3,):
        @classmethod
        def FromString(cls, s: builtin___bytes) -> PermissionQuery: ...
    else:
        @classmethod
        def FromString(cls, s: typing___Union[builtin___bytes, builtin___buffer, builtin___unicode]) -> PermissionQuery: ...
    def MergeFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def CopyFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    if sys.version_info >= (3,):
        def HasField(self, field_name: typing_extensions___Literal[u"channel_id",u"flush",u"permissions"]) -> builtin___bool: ...
        def ClearField(self, field_name: typing_extensions___Literal[u"channel_id",u"flush",u"permissions"]) -> None: ...
    else:
        def HasField(self, field_name: typing_extensions___Literal[u"channel_id",b"channel_id",u"flush",b"flush",u"permissions",b"permissions"]) -> builtin___bool: ...
        def ClearField(self, field_name: typing_extensions___Literal[u"channel_id",b"channel_id",u"flush",b"flush",u"permissions",b"permissions"]) -> None: ...

class CodecVersion(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    alpha = ... # type: builtin___int
    beta = ... # type: builtin___int
    prefer_alpha = ... # type: builtin___bool
    opus = ... # type: builtin___bool

    def __init__(self,
        *,
        alpha : builtin___int,
        beta : builtin___int,
        prefer_alpha : builtin___bool,
        opus : typing___Optional[builtin___bool] = None,
        ) -> None: ...
    if sys.version_info >= (3,):
        @classmethod
        def FromString(cls, s: builtin___bytes) -> CodecVersion: ...
    else:
        @classmethod
        def FromString(cls, s: typing___Union[builtin___bytes, builtin___buffer, builtin___unicode]) -> CodecVersion: ...
    def MergeFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def CopyFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    if sys.version_info >= (3,):
        def HasField(self, field_name: typing_extensions___Literal[u"alpha",u"beta",u"opus",u"prefer_alpha"]) -> builtin___bool: ...
        def ClearField(self, field_name: typing_extensions___Literal[u"alpha",u"beta",u"opus",u"prefer_alpha"]) -> None: ...
    else:
        def HasField(self, field_name: typing_extensions___Literal[u"alpha",b"alpha",u"beta",b"beta",u"opus",b"opus",u"prefer_alpha",b"prefer_alpha"]) -> builtin___bool: ...
        def ClearField(self, field_name: typing_extensions___Literal[u"alpha",b"alpha",u"beta",b"beta",u"opus",b"opus",u"prefer_alpha",b"prefer_alpha"]) -> None: ...

class UserStats(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    class Stats(google___protobuf___message___Message):
        DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
        good = ... # type: builtin___int
        late = ... # type: builtin___int
        lost = ... # type: builtin___int
        resync = ... # type: builtin___int

        def __init__(self,
            *,
            good : typing___Optional[builtin___int] = None,
            late : typing___Optional[builtin___int] = None,
            lost : typing___Optional[builtin___int] = None,
            resync : typing___Optional[builtin___int] = None,
            ) -> None: ...
        if sys.version_info >= (3,):
            @classmethod
            def FromString(cls, s: builtin___bytes) -> UserStats.Stats: ...
        else:
            @classmethod
            def FromString(cls, s: typing___Union[builtin___bytes, builtin___buffer, builtin___unicode]) -> UserStats.Stats: ...
        def MergeFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
        def CopyFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
        if sys.version_info >= (3,):
            def HasField(self, field_name: typing_extensions___Literal[u"good",u"late",u"lost",u"resync"]) -> builtin___bool: ...
            def ClearField(self, field_name: typing_extensions___Literal[u"good",u"late",u"lost",u"resync"]) -> None: ...
        else:
            def HasField(self, field_name: typing_extensions___Literal[u"good",b"good",u"late",b"late",u"lost",b"lost",u"resync",b"resync"]) -> builtin___bool: ...
            def ClearField(self, field_name: typing_extensions___Literal[u"good",b"good",u"late",b"late",u"lost",b"lost",u"resync",b"resync"]) -> None: ...

    session = ... # type: builtin___int
    stats_only = ... # type: builtin___bool
    certificates = ... # type: google___protobuf___internal___containers___RepeatedScalarFieldContainer[builtin___bytes]
    udp_packets = ... # type: builtin___int
    tcp_packets = ... # type: builtin___int
    udp_ping_avg = ... # type: builtin___float
    udp_ping_var = ... # type: builtin___float
    tcp_ping_avg = ... # type: builtin___float
    tcp_ping_var = ... # type: builtin___float
    celt_versions = ... # type: google___protobuf___internal___containers___RepeatedScalarFieldContainer[builtin___int]
    address = ... # type: builtin___bytes
    bandwidth = ... # type: builtin___int
    onlinesecs = ... # type: builtin___int
    idlesecs = ... # type: builtin___int
    strong_certificate = ... # type: builtin___bool
    opus = ... # type: builtin___bool

    @property
    def from_client(self) -> UserStats.Stats: ...

    @property
    def from_server(self) -> UserStats.Stats: ...

    @property
    def version(self) -> Version: ...

    def __init__(self,
        *,
        session : typing___Optional[builtin___int] = None,
        stats_only : typing___Optional[builtin___bool] = None,
        certificates : typing___Optional[typing___Iterable[builtin___bytes]] = None,
        from_client : typing___Optional[UserStats.Stats] = None,
        from_server : typing___Optional[UserStats.Stats] = None,
        udp_packets : typing___Optional[builtin___int] = None,
        tcp_packets : typing___Optional[builtin___int] = None,
        udp_ping_avg : typing___Optional[builtin___float] = None,
        udp_ping_var : typing___Optional[builtin___float] = None,
        tcp_ping_avg : typing___Optional[builtin___float] = None,
        tcp_ping_var : typing___Optional[builtin___float] = None,
        version : typing___Optional[Version] = None,
        celt_versions : typing___Optional[typing___Iterable[builtin___int]] = None,
        address : typing___Optional[builtin___bytes] = None,
        bandwidth : typing___Optional[builtin___int] = None,
        onlinesecs : typing___Optional[builtin___int] = None,
        idlesecs : typing___Optional[builtin___int] = None,
        strong_certificate : typing___Optional[builtin___bool] = None,
        opus : typing___Optional[builtin___bool] = None,
        ) -> None: ...
    if sys.version_info >= (3,):
        @classmethod
        def FromString(cls, s: builtin___bytes) -> UserStats: ...
    else:
        @classmethod
        def FromString(cls, s: typing___Union[builtin___bytes, builtin___buffer, builtin___unicode]) -> UserStats: ...
    def MergeFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def CopyFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    if sys.version_info >= (3,):
        def HasField(self, field_name: typing_extensions___Literal[u"address",u"bandwidth",u"from_client",u"from_server",u"idlesecs",u"onlinesecs",u"opus",u"session",u"stats_only",u"strong_certificate",u"tcp_packets",u"tcp_ping_avg",u"tcp_ping_var",u"udp_packets",u"udp_ping_avg",u"udp_ping_var",u"version"]) -> builtin___bool: ...
        def ClearField(self, field_name: typing_extensions___Literal[u"address",u"bandwidth",u"celt_versions",u"certificates",u"from_client",u"from_server",u"idlesecs",u"onlinesecs",u"opus",u"session",u"stats_only",u"strong_certificate",u"tcp_packets",u"tcp_ping_avg",u"tcp_ping_var",u"udp_packets",u"udp_ping_avg",u"udp_ping_var",u"version"]) -> None: ...
    else:
        def HasField(self, field_name: typing_extensions___Literal[u"address",b"address",u"bandwidth",b"bandwidth",u"from_client",b"from_client",u"from_server",b"from_server",u"idlesecs",b"idlesecs",u"onlinesecs",b"onlinesecs",u"opus",b"opus",u"session",b"session",u"stats_only",b"stats_only",u"strong_certificate",b"strong_certificate",u"tcp_packets",b"tcp_packets",u"tcp_ping_avg",b"tcp_ping_avg",u"tcp_ping_var",b"tcp_ping_var",u"udp_packets",b"udp_packets",u"udp_ping_avg",b"udp_ping_avg",u"udp_ping_var",b"udp_ping_var",u"version",b"version"]) -> builtin___bool: ...
        def ClearField(self, field_name: typing_extensions___Literal[u"address",b"address",u"bandwidth",b"bandwidth",u"celt_versions",b"celt_versions",u"certificates",b"certificates",u"from_client",b"from_client",u"from_server",b"from_server",u"idlesecs",b"idlesecs",u"onlinesecs",b"onlinesecs",u"opus",b"opus",u"session",b"session",u"stats_only",b"stats_only",u"strong_certificate",b"strong_certificate",u"tcp_packets",b"tcp_packets",u"tcp_ping_avg",b"tcp_ping_avg",u"tcp_ping_var",b"tcp_ping_var",u"udp_packets",b"udp_packets",u"udp_ping_avg",b"udp_ping_avg",u"udp_ping_var",b"udp_ping_var",u"version",b"version"]) -> None: ...

class RequestBlob(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    session_texture = ... # type: google___protobuf___internal___containers___RepeatedScalarFieldContainer[builtin___int]
    session_comment = ... # type: google___protobuf___internal___containers___RepeatedScalarFieldContainer[builtin___int]
    channel_description = ... # type: google___protobuf___internal___containers___RepeatedScalarFieldContainer[builtin___int]

    def __init__(self,
        *,
        session_texture : typing___Optional[typing___Iterable[builtin___int]] = None,
        session_comment : typing___Optional[typing___Iterable[builtin___int]] = None,
        channel_description : typing___Optional[typing___Iterable[builtin___int]] = None,
        ) -> None: ...
    if sys.version_info >= (3,):
        @classmethod
        def FromString(cls, s: builtin___bytes) -> RequestBlob: ...
    else:
        @classmethod
        def FromString(cls, s: typing___Union[builtin___bytes, builtin___buffer, builtin___unicode]) -> RequestBlob: ...
    def MergeFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def CopyFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    if sys.version_info >= (3,):
        def ClearField(self, field_name: typing_extensions___Literal[u"channel_description",u"session_comment",u"session_texture"]) -> None: ...
    else:
        def ClearField(self, field_name: typing_extensions___Literal[u"channel_description",b"channel_description",u"session_comment",b"session_comment",u"session_texture",b"session_texture"]) -> None: ...

class ServerConfig(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    max_bandwidth = ... # type: builtin___int
    welcome_text = ... # type: typing___Text
    allow_html = ... # type: builtin___bool
    message_length = ... # type: builtin___int
    image_message_length = ... # type: builtin___int
    max_users = ... # type: builtin___int

    def __init__(self,
        *,
        max_bandwidth : typing___Optional[builtin___int] = None,
        welcome_text : typing___Optional[typing___Text] = None,
        allow_html : typing___Optional[builtin___bool] = None,
        message_length : typing___Optional[builtin___int] = None,
        image_message_length : typing___Optional[builtin___int] = None,
        max_users : typing___Optional[builtin___int] = None,
        ) -> None: ...
    if sys.version_info >= (3,):
        @classmethod
        def FromString(cls, s: builtin___bytes) -> ServerConfig: ...
    else:
        @classmethod
        def FromString(cls, s: typing___Union[builtin___bytes, builtin___buffer, builtin___unicode]) -> ServerConfig: ...
    def MergeFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def CopyFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    if sys.version_info >= (3,):
        def HasField(self, field_name: typing_extensions___Literal[u"allow_html",u"image_message_length",u"max_bandwidth",u"max_users",u"message_length",u"welcome_text"]) -> builtin___bool: ...
        def ClearField(self, field_name: typing_extensions___Literal[u"allow_html",u"image_message_length",u"max_bandwidth",u"max_users",u"message_length",u"welcome_text"]) -> None: ...
    else:
        def HasField(self, field_name: typing_extensions___Literal[u"allow_html",b"allow_html",u"image_message_length",b"image_message_length",u"max_bandwidth",b"max_bandwidth",u"max_users",b"max_users",u"message_length",b"message_length",u"welcome_text",b"welcome_text"]) -> builtin___bool: ...
        def ClearField(self, field_name: typing_extensions___Literal[u"allow_html",b"allow_html",u"image_message_length",b"image_message_length",u"max_bandwidth",b"max_bandwidth",u"max_users",b"max_users",u"message_length",b"message_length",u"welcome_text",b"welcome_text"]) -> None: ...

class SuggestConfig(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    version = ... # type: builtin___int
    positional = ... # type: builtin___bool
    push_to_talk = ... # type: builtin___bool

    def __init__(self,
        *,
        version : typing___Optional[builtin___int] = None,
        positional : typing___Optional[builtin___bool] = None,
        push_to_talk : typing___Optional[builtin___bool] = None,
        ) -> None: ...
    if sys.version_info >= (3,):
        @classmethod
        def FromString(cls, s: builtin___bytes) -> SuggestConfig: ...
    else:
        @classmethod
        def FromString(cls, s: typing___Union[builtin___bytes, builtin___buffer, builtin___unicode]) -> SuggestConfig: ...
    def MergeFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def CopyFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    if sys.version_info >= (3,):
        def HasField(self, field_name: typing_extensions___Literal[u"positional",u"push_to_talk",u"version"]) -> builtin___bool: ...
        def ClearField(self, field_name: typing_extensions___Literal[u"positional",u"push_to_talk",u"version"]) -> None: ...
    else:
        def HasField(self, field_name: typing_extensions___Literal[u"positional",b"positional",u"push_to_talk",b"push_to_talk",u"version",b"version"]) -> builtin___bool: ...
        def ClearField(self, field_name: typing_extensions___Literal[u"positional",b"positional",u"push_to_talk",b"push_to_talk",u"version",b"version"]) -> None: ...
